#!/bin/sh

GW="$(batctl gwl | grep '=>' | cut -f 2 -d ' ')"
GW_MAC="$(batctl tg | grep "$GW" | cut -d ' ' -f 3)"

COUNT=0
for gw_mac in "$GW_MAC" ; do
  GW_ADDR=$(batctl dc | grep "$gw_mac" | sed -e 's/^[^0-9]*\([0-9]\+\)/\1/' | cut -d ' ' -f 1)
  COUNT=$(expr $COUNT + 1)
done

[[ "$COUNT" -eq 1 ]] || exit 1

/usr/sbin/ddhcpdctl -o "3;4;${GW_ADDR}" -o "6;4;${GW_ADDR}"
