#!/usr/bin/lua
local site = require('gluon.site')
local uci = require('simple-uci').cursor()
if site.ddhcpd then
  local enabled = site.ddhcpd.enabled()
  enabled = enabled == '0' and '0' or enabled and '1' or '0'
  uci:section('ddhcpd', 'settings', 'settings', {
    enabled = uci:get('ddhcpd', 'settings', 'enabled') or enabled,
    block_network = site.ddhcpd.range()
  })
  uci:section('ddhcpd','dhcp_option','server_identify',{
    code=54,
    len=4,
    payload=site.next_node.ip4()
  })
  uci:delete('ddhcpd','broadcast')
  cidr=tonumber(string.gsub(site:prefix4(),"[%w\.]+/(%d+)","%1"),10)
  netmask=''
  for i=1,3 do
    netmask=netmask..tostring(256-2^math.max(0,8-cidr))..'.'
    cidr=math.max(0,cidr-8)
  end
  netmask=netmask..tostring(256-2^math.max(0,8-cidr))
  uci:section('ddhcpd','dhcp_option','netmask',{
    code=1,
    len=4,
    payload=netmask,
  })
  uci:save('ddhcpd')
end
