#!/usr/bin/lua
local a=require'gluon.site'
local e=require('simple-uci').cursor()
e:section('ddhcpd','dhcp_option','server_identify',{
code=54,
len=4,
payload=a.next_node.ip4()
})
e:delete('ddhcpd','dhcp_option','broadcast')
cidr=tonumber(string.gsub(a:prefix4(),"[%w\.]+/(%d+)","%1"),10)
nm='' 
for i=1,3 do
nm=nm..tostring(256-2^math.max(0,8-cidr))..'.'
cidr=math.max(0,cidr-8)
end
nm=nm..tostring(256-2^math.max(0,8-cidr))
e:section('ddhcpd','dhcp_option','netmask',{
code=1,
len=4,
payload=nm,
})
e:save('ddhcpd')
