#!/bin/sh /etc/rc.common

USE_PROCD=1
START=50

DAEMON=/usr/sbin/ddhcpd
MAXDELAY=10

start_service() {
        [ -x /lib/gluon/ddhcpd/arguments ] || exit 1

        local ifdump="$(ubus call network.interface dump)"
        
        local clientdevs=$(for dev in $(echo "$ifdump" | jsonfilter -e "@.interface[@.interface='client' && @.up=true].device"); do echo " -c $dev ";done;)
        local servicedevs=$(for dev in $(echo "$ifdump" | jsonfilter -e "@.interface[@.interface='client' && @.up=true].device"); do echo " -i $dev ";done;)

        procd_open_instance
        procd_set_param command $DAEMON -D $(/lib/gluon/ddhcpd/arguments) -b 2 -s 1 ${clientdevs} ${servicedevs}
        procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
        procd_set_param stderr 1
        procd_close_instance
}
