#!/bin/sh /etc/rc.common

START=90
USE_PROCD=1

NAME=ddhcpd
DAEMON=/usr/sbin/ddhcpd
MAXDELAY=10

validate_section_ddhcpd() {
  uci_validate_section "$NAME" ddhcpd settings \
  'dhcp_interface:string:br-client' \
  'server_interface:string:br-client' \
  'block_size_pow:uinteger:2' \
  'spare_blocks:uinteger:1' \
  'timeout:uinteger:30' \
  'block_network:cidr4' \
  'dhcp_lease_time:uinteger:300'
}

dhcp_option() {
  local cfg="$1" code len payload
  config_get code "$cfg" code
  config_get len "$cfg" len
  config_get payload "$cfg" payload
  procd_append_param command -o "$code:$len:$payload"
}

convert_leasetime() {
    local l0=0 l1=0 l2=0 l3=0
    local dnsmasq_style="$1"
    local value="${dnsmasq_style:0: -1}"
    local suffix="${dnsmasq_style: -1}"
    [ "$suffix" == "h" ] && value="$(expr $value \* 3600)"
    [ "$suffix" == "m" ] && value="$(expr $value \* 60)"

    [ "$value" -gt 16581375 ] && {
        l3="$(expr $value / 255)"
        value="$(expr $value % 255)"
    }
    [ "$value" -gt 65025 ] && {
        l2=$(expr $value / 255)
        value="$(expr $value % 255)"
    }
    [ "$value" -gt 255 ] && {
        l1=$(expr $value / 255)
        value="$(expr $value % 255)"
    }
    l0="$(expr $value % 255)"

    echo "$l3.$l2.$l1.$l0"
}

dhcp_config() {
  local cfg="$1" ignore leasetime interface
  config_get ignore "$cfg" ignore
  [ "$ignore" == 1 ] && return
  config_get leasetime "$cfg" leasetime
  config_get interface "$cfg" interface
  procd_append_param command -o "1:4:$(uci get network.$interface.netmask)"
  procd_append_param command -o "3:4:$(uci get network.$interface.ipaddr)" # router
  procd_append_param command -o "6:4:$(uci get network.$interface.ipaddr)" # dns
  local pure_leasetime="$(convert_leasetime $leasetime)"
  procd_append_param command -o "51:4:$pure_leasetime"
}

start_service() {
  procd_open_instance
  procd_set_param command $DAEMON -D 

  config_load "dhcp"
  config_foreach dhcp_config dhcp

  config_load "${NAME}"

  validate_section_ddhcpd || {
    echo "validation failed"
    return 1
  }

  procd_append_param command -s "$spare_blocks"
  procd_append_param command -b "$block_size_pow"
  procd_append_param command -c "$dhcp_interface"
  procd_append_param command -i "$server_interface"
  procd_append_param command -N "$block_network"
  procd_append_param command -H "/etc/ddhcpd.hook"
  config_foreach dhcp_option dhcp_option
  [[ -f /lib/gluon/ddhcpd/arguments ]] && procd_append_param command $(/lib/gluon/ddhcpd/arguments)
  procd_set_param respawn
  procd_set_param netdev "$dhcp_interface"
  [ "$dhcp_interface" == "$server_interface" ] || procd_append_param netdev "$server_interface"
  procd_set_param stderr 1
  procd_close_instance
}

service_triggers() {
  procd_add_config_trigger "config.change" "ddhcpd" /etc/init.d/ddhcpd restart
  procd_add_interface_trigger "interface.*" "$dhcp_interface" /etc/init.d/ddhcpd restart
  [ "$dhcp_interface" == "$server_interface" ] || \
      procd_add_interface_trigger "interface.*" "$server_interface" /etc/init.d/ddhcpd restart
}
