#!/bin/sh /etc/rc.common

start() {
        rm -f /tmp/ddhcpd_ctl
        ddhcpd -d -o "3;4;10,116,254,254" -o "1;4;255,255,128,0" -o "28;4;10,116,255,255" -o "54;4;10.116.254.254" -N 10.116.224.0/20 -b 2 -s 1 -c br-client -i br-client
        return 0
}

stop() {
        kill  $(pgrep ddhcpd -f)
        return 0
}
